In [1]:
from ann import cost, cost_regL2, backprop, backprop2, predict, feedForward
from utils import checkNNGradients

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from scipy.io import loadmat, savemat
from scipy.optimize import minimize
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report

testData = pd.read_csv("winequality-test.txt")
trainData = pd.read_csv("winequality-train.txt")

X_train = trainData.iloc[:, :-1]
y_train = trainData.iloc[:, -1:]

y_test = testData.iloc[:, -1:]
X_test = testData.iloc[:, :-1]

encoder = OneHotEncoder(sparse_output=False)
y_train = encoder.fit_transform(y_train)

layer_sizes = [X_train.shape[1], 100, y_train.shape[1]]
epsilon = 0.12
theta_list = []

for i in range(len(layer_sizes) - 1):
    theta_list.append(np.random.rand(layer_sizes[i + 1], layer_sizes[i] + 1) * 2 * epsilon - epsilon)

iterations = 1000
lambda_ = 1
alpha = 0.1

for i in range(iterations):
    cost, grads = backprop(theta_list, X_train, y_train, lambda_)

    for j in range(len(theta_list)):
        theta_list[j] -= alpha * grads[j]

predictions = predict(theta_list, X_train)

# Datos entrenamiento
accuracy = accuracy_score(np.argmax(y_train, axis=1), predictions)
print(f'Precisión del perceptrón: {accuracy * 100:.2f}%')

conf_matrix = confusion_matrix(np.argmax(y_train, axis=1), predictions)
print(f'Matriz de confusión:\n {conf_matrix}')

mse = mean_squared_error(np.argmax(y_train, axis=1), predictions)
print(f'Error cuadratico medio: {mse:.2f} \n')

# Datos reales
predictions = predict(theta_list, X_test)

accuracy = accuracy_score(y_test, predictions)
print(f'Precisión del perceptrón: {accuracy * 100:.2f}%')

conf_matrix = confusion_matrix(y_test, predictions)
print(f'Matriz de confusión:\n {conf_matrix}')

mse = mean_squared_error(y_test, predictions)
print(f'Error cuadratico medio: {mse:.2f} \n')

# report_sklearn = classification_report(y_test, predictions)
# print(report_sklearn)

# print("\nExplicaciones:")
# print("Precision: Es la proporción de instancias clasificadas como positivas que son realmente positivas.")
# print("Recall: Es la proporción de instancias positivas que fueron correctamente clasificadas como positivas.")
# print("F1-score: Es la media armónica ponderada de precision y recall. Es útil cuando hay desbalance de clases.")
# print("Support: Es el número real de ocurrencias de la clase en el conjunto de prueba.")
# print("Accuracy: Es la proporción de instancias correctamente clasificadas en el conjunto de prueba.")
# print("Macro avg: Es el promedio no ponderado de precision, recall y f1-score para todas las clases.")
# print("Weighted avg: Es el promedio ponderado por el soporte (número de instancias) de precision, recall y f1-score.")

# SVM
print('------------------------------\n')
print('DATOS DEL SUPPORT VECTOR MACHINE (SVM)\n')

svm_classifier = SVC(kernel='linear', C=1.0)
svm_classifier.fit(X_train, np.argmax(y_train, axis=1))

# Datos de test
predictions = svm_classifier.predict(X_test)

accuracy = accuracy_score(y_test, predictions)
print(f'Precisión del SVM: {accuracy * 100:.2f}%')

conf_matrix = confusion_matrix(y_test, predictions)
print(f'Matriz de confusión:\n {conf_matrix}')

mse = mean_squared_error(y_test, predictions)
print(f'Error cuadrático medio: {mse:.2f} \n')

Precisión del perceptrón: 86.37%
Matriz de confusión:
 [[925   0]
 [146   0]]
Error cuadratico medio: 0.14 

Precisión del perceptrón: 86.55%
Matriz de confusión:
 [[457   0]
 [ 71   0]]
Error cuadratico medio: 0.13 

------------------------------

DATOS DEL SUPPORT VECTOR MACHINE (SVM)

Precisión del SVM: 86.55%
Matriz de confusión:
 [[457   0]
 [ 71   0]]
Error cuadrático medio: 0.13 



### Teoria

Justificar los datos del perceptron respecto a SVM



